(self.AMP=self.AMP||[]).push({n:"amp-facebook-like",v:"2101211748002",m:0,f:(function(AMP,_){
'use strict';var aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b};function ba(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}ba(this);"function"===typeof Symbol&&Symbol("x");var r;
if("function"==typeof Object.setPrototypeOf)r=Object.setPrototypeOf;else{var t;a:{var ca={a:!0},A={};try{A.__proto__=ca;t=A.a;break a}catch(a){}t=!1}r=t?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var da=r;function ea(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var fa=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function B(a){var b=Object.create(null);if(!a)return b;for(var c;c=fa.exec(a);){var d=ea(c[1],c[1]),e=c[2]?ea(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var C="";
function D(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=B(a.location.originalHash||a.location.hash);var c=B(a.location.search);C||(C=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012101211748002");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2101211748002",rtvVersion:C};b=a.__AMP_MODE=b}return b};var ha=Object.prototype.toString;var E=self.AMP_CONFIG||{},ia=("string"==typeof E.cdnProxyRegex?new RegExp(E.cdnProxyRegex):E.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function ja(a){if(!self.document||!self.document.head||self.location&&ia.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var F={thirdParty:E.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:E.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof E.thirdPartyFrameRegex?new RegExp(E.thirdPartyFrameRegex):E.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:E.cdnUrl||ja("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ia,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:E.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:E.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:E.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:E.geoApiUrl||ja("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var G=self.__AMP_LOG;function ka(){if(!G.user)throw Error("failed to call initLogConstructor");return G.user}function I(){if(G.dev)return G.dev;throw Error("failed to call initLogConstructor");}function J(a,b,c,d,e){ka().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};function la(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return ma(a,b)}function na(a,b){var c=K(a);c=K(c);c=c.isSingleDoc()?c.win:c;return ma(c,b)}function K(a){return a.nodeType?la((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function ma(a,b){var c=a.__AMP_SERVICES;c||(c=a.__AMP_SERVICES={});a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function L(a){return a||{}};var M;function oa(a,b){var c=a,d=b;var e=function(f){try{return d(f)}catch(h){throw self.__AMP_REPORT_ERROR(h),h;}};var g=pa();c.addEventListener("message",e,g?void 0:!1);return function(){c&&c.removeEventListener("message",e,g?void 0:!1);e=c=d=null}}function pa(){if(void 0!==M)return M;M=!1;try{var a={get capture(){M=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return M};function qa(a,b){return oa(a,b)};function P(){this.B=100;this.l=this.o=0;this.j=Object.create(null)}P.prototype.has=function(a){return!!this.j[a]};P.prototype.get=function(a){var b=this.j[a];if(b)return b.access=++this.l,b.payload};P.prototype.put=function(a,b){this.has(a)||this.o++;this.j[a]={payload:b,access:this.l};if(!(this.o<=this.B)){I().warn("lru-cache","Trimming LRU cache");a=this.j;var c=this.l+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var g=d}}void 0!==g&&(delete a[g],this.o--)}};L({c:!0,v:!0,a:!0,ad:!0});var Q,ra;
function R(a){Q||(Q=self.document.createElement("a"),ra=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new P));var b=ra,c=Q;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a};var S,sa="Webkit webkit Moz moz ms O o".split(" ");function ta(a){var b=a.style;if("border".startsWith("--"))b="border";else{S||(S=Object.create(null));var c=S.border;if(!c){c="border";if(void 0===b.border){var d;b:{for(d=0;d<sa.length;d++){var e=sa[d]+"Border";if(void 0!==b[e]){d=e;break b}}d=""}void 0!==b[d]&&(c=d)}S.border=c}b=c}b&&(b.startsWith("--")?a.style.setProperty(b,"none"):a.style[b]="none")};function ua(a){a=parseFloat(a);return"number"===typeof a&&isFinite(a)?a:void 0};function T(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};var U={};
function va(a,b){J("facebook","Attribute type required for <amp-ad>: %s",b);var c=0;for(var d=a;d&&d!=d.parent;d=d.parent)c++;c=String(c)+"-"+wa(a);var e=d={},g=b.dataset,f;for(f in g)f.startsWith("vars")||(e[f]=g[f]);if(f=b.getAttribute("json")){f=T(f);if(void 0===f)throw ka().createError("Error parsing JSON in json attribute in element %s",b);for(var h in f)e[h]=f[h]}h=d;d=Date.now();e=b.getAttribute("width");f=b.getAttribute("height");h=h?h:{};h.width=ua(e);h.height=ua(f);b.getAttribute("title")&&(h.title=
b.getAttribute("title"));var n=a.location.href;"about:srcdoc"==n&&(n=a.parent.location.href);var m=K(b),y=na(b,"documentInfo").get();e=na(b,"viewer").getUnconfirmedReferrerUrl();var p=b.ownerDocument.body;g=f=0;for(var v=b;v&&v!=p;v=v.offsetParent)f+=v.offsetLeft,g+=v.offsetTop;p=b.offsetWidth;v=b.offsetHeight;var z={left:f,top:g,width:p,height:v,bottom:g+v,right:f+p,x:f,y:g};f=h;g=F.thirdParty+"/2101211748002/ampcontext-v0.js";p=y.sourceUrl;v=y.canonicalUrl;y=y.pageViewId;n={href:n};var Ba=b.tagName,
Ca={localDev:!1,development:D().development,esm:!1,minified:!0,lite:D().lite,test:!1,log:D().log,version:D().version,rtvVersion:D().rtvVersion},Da=!(!a.AMP_CONFIG||!a.AMP_CONFIG.canary);m=!m.isVisible();z=z?{left:z.left,top:z.top,width:z.width,height:z.height}:null;var q=b;for(var w=[],k=0;q&&1==q.nodeType&&25>k;){var x="";q.id&&(x="/"+q.id);var X=q.nodeName.toLowerCase(),l=w,H=l.push;x=""+X+x;X=q.nodeName;for(var Y=0,N=0,O=q.previousElementSibling;O&&25>N&&100>Y;)O.nodeName==X&&N++,Y++,O=O.previousElementSibling;
H.call(l,x+(25>N&&100>Y?"."+N:""));k++;q=q.parentElement}q=w.join();w=q.length;k=5381;for(l=0;l<w;l++)k=33*k^q.charCodeAt(l);q=String(k>>>0);if(a.__AMP__EXPERIMENT_TOGGLES)a=a.__AMP__EXPERIMENT_TOGGLES;else{a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);w=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var u in a.AMP_CONFIG)k=a.AMP_CONFIG[u],"number"===typeof k&&0<=k&&1>=k&&(w[u]=Math.random()<k);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length&&
(u=a.AMP_CONFIG["allow-doc-opt-in"],k=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]')))for(k=k.getAttribute("content").split(","),l=0;l<k.length;l++)-1!=u.indexOf(k[l])&&(w[k[l]]=!0);u=Object;k=u.assign;l="";try{"localStorage"in a&&(l=a.localStorage.getItem("amp-experiment-toggles"))}catch(Ma){I().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}l=l?l.split(/\s*,\s*/g):[];H=Object.create(null);for(x=0;x<l.length;x++)0!=l[x].length&&("-"==l[x][0]?H[l[x].substr(1)]=
!1:H[l[x]]=!0);k.call(u,w,H);if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length)for(u=a.AMP_CONFIG["allow-url-opt-in"],a=B(a.location.originalHash||a.location.hash),k=0;k<u.length;k++)l=a["e-"+u[k]],"1"==l&&(w[u[k]]=!0),"0"==l&&(w[u[k]]=!1);a=w}f._context=L({ampcontextVersion:"2101211748002",ampcontextFilepath:g,sourceUrl:p,referrer:e,canonicalUrl:v,pageViewId:y,location:n,startTime:d,tagName:Ba,mode:Ca,canary:Da,hidden:m,initialLayoutRect:z,
domFingerprint:q,experimentToggles:a,sentinel:c});(b=b.getAttribute("src"))&&(h.src=b);d=h;d.type="facebook";Object.assign(d._context,void 0);return d}
function xa(a,b){var c=void 0===c?{}:c;var d=void 0===c.disallowCustom?!1:c.disallowCustom,e=void 0===c.allowFullscreen?!1:c.allowFullscreen,g=c.initialIntersection;c=va(a,b);g&&(c._context.initialIntersection=g);var f=a.document.createElement("iframe");U[c.type]||(U[c.type]=0);U[c.type]+=1;var h=b.getAmpDoc();a=ya(a,h,d);var n=R(a).hostname;h=JSON.stringify(L({host:n,type:c.type,count:U[c.type],attributes:c}));f.src=a;f.ampLocation=R(a);f.name=h;c.width&&(f.width=c.width);c.height&&(f.height=c.height);
c.title&&(f.title=c.title);e&&f.setAttribute("allowfullscreen","true");f.setAttribute("scrolling","no");ta(f);f.onload=function(){this.readyState="complete"};f.setAttribute("allow","sync-xhr 'none';");["facebook"].includes("facebook")||za(f);f.setAttribute("data-amp-3p-sentinel",c._context.sentinel);return f}
function ya(a,b,c){if(c)var d=null;else if(b=b.getMetaByName("amp-3p-iframe-src")){d=void 0===d?"source":d;J(null!=b,"%s %s must be available",'meta[name="amp-3p-iframe-src"]',d);c=b;"string"==typeof c&&(c=R(c));var e;(e="https:"==c.protocol||"localhost"==c.hostname||"127.0.0.1"==c.hostname)||(c=c.hostname,e=c.length-10,e=0<=e&&c.indexOf(".localhost",e)==e);J(e||/^(\/\/)/.test(b),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',
'meta[name="amp-3p-iframe-src"]',d,b);J(-1==b.indexOf("?"),"3p iframe url must not include query string %s in element %s.",b,b);d=R(b);J("localhost"==d.hostname&&!0||d.origin!=R(a.location.href).origin,"3p iframe url must not be on the same origin as the current document %s (%s) in element %s. See https://github.com/ampproject/amphtml/blob/master/spec/amp-iframe-origin-policy.md for details.",b,d.origin,b);d=b+"?2101211748002"}else d=null;d||(a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN=a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN||
"d-"+wa(a),d="https://"+a.__AMP_DEFAULT_BOOTSTRAP_SUBDOMAIN+("."+F.thirdPartyFrameHost+"/2101211748002/frame.html"));return d}function wa(a){if(a.crypto&&a.crypto.getRandomValues){var b=new Uint32Array(2);a.crypto.getRandomValues(b);var c=String(b[0])+b[1]}else c=String(a.Math.random()).substr(2)+"0";return c}
function za(a){if(a.sandbox&&a.sandbox.supports){for(var b=["allow-top-navigation-by-user-activation","allow-popups-to-escape-sandbox"],c=0;c<b.length;c++){var d=b[c];if(!a.sandbox.supports(d)){I().info("3p-frame","Iframe doesn't support %s",d);return}}a.sandbox=b.join(" ")+" allow-forms allow-modals allow-pointer-lock allow-popups allow-same-origin allow-scripts"}};function Aa(a){if(!Ea(a))return null;var b=a.indexOf("{");try{return JSON.parse(a.substr(b))}catch(c){return I().error("MESSAGING","Failed to parse message: "+a,c),null}}function Ea(a){return"string"==typeof a&&0==a.indexOf("amp-")&&-1!=a.indexOf("{")};function Fa(a,b,c){var d=a.listeningFors;!d&&c&&(d=a.listeningFors=Object.create(null));a=d||null;if(!a)return a;var e=a[b];!e&&c&&(e=a[b]=[]);return e||null}function Ga(a,b){var c=b.getAttribute("data-amp-3p-sentinel");a=Fa(a,c,!0);for(c=0;c<a.length;c++){var d=a[c];if(d.frame===b){var e=d;break}}e||(e={frame:b,events:Object.create(null)},a.push(e));return e.events}
function Ha(a){for(var b=L({sentinel:"unlisten"}),c=a.length-1;0<=c;c--){var d=a[c];if(!d.frame.contentWindow){a.splice(c,1);var e=d.events,g;for(g in e)e[g].splice(0,Infinity).forEach(function(f){f(b)})}}}
function Ia(a){a.listeningFors||a.addEventListener("message",function(b){if(b.data){var c=Ja(b.data);if(c&&c.sentinel){var d=b.source;var e=Fa(a,c.sentinel);if(e){for(var g,f=0;f<e.length;f++){var h=e[f],n=h.frame.contentWindow;if(n){var m;if(!(m=d==n))b:{for(m=d;m&&m!=m.parent;m=m.parent)if(m==n){m=!0;break b}m=!1}if(m){g=h;break}}else setTimeout(Ha,0,e)}d=g?g.events:null}else d=e;var y=d;if(y){var p=y[c.type];if(p)for(p=p.slice(),d=0;d<p.length;d++)(0,p[d])(c,b.source,b.origin,b)}}}})}
function Ka(a,b){function c(h,n,m,y){if("amp"==h.sentinel){if(n!=a.contentWindow)return;var p="null"==m&&void 0;if(e!=m&&!p)return}n==a.contentWindow&&("unlisten"==h.sentinel?f():b(h,n,m,y))}var d=a.ownerDocument.defaultView;Ia(d);d=Ga(d,a);var e=R(a.src).origin,g=d["embed-size"]||(d["embed-size"]=[]);g.push(c);var f=function(){if(c){var h=g.indexOf(c);-1<h&&g.splice(h,1);b=g=c=null}}}
function Ja(a){"string"==typeof a&&(a="{"==a.charAt(0)?T(a,function(b){I().warn("IFRAME-HELPER","Postmessage could not be parsed. Is it in a valid JSON format?",b)})||null:Ea(a)?Aa(a):null);return a};function V(a){var b=AMP.BaseElement.call(this,a)||this;b.h=null;a=a.hasAttribute("data-locale")?a.getAttribute("data-locale"):window.navigator.language.replace("-","_");b.C=a;b.A=null;return b}var W=AMP.BaseElement;V.prototype=aa(W.prototype);V.prototype.constructor=V;if(da)da(V,W);else for(var Z in W)if("prototype"!=Z)if(Object.defineProperties){var La=Object.getOwnPropertyDescriptor(W,Z);La&&Object.defineProperty(V,Z,La)}else V[Z]=W[Z];V.F=W.prototype;V.prototype.renderOutsideViewport=function(){return.75};
V.prototype.preconnectCallback=function(a){var b=la(this.win,"preconnect");b.url(this.getAmpDoc(),"https://facebook.com",a);b.preload(this.getAmpDoc(),"https://connect.facebook.net/"+this.C+"/sdk.js","script");var c=this.getAmpDoc(),d=ya(this.win,c,void 0);b.preload(c,d,"document");b.preload(c,F.thirdParty+"/2101211748002/f.js","script")};V.prototype.isLayoutSupported=function(a){return"fixed"==a||"fixed-height"==a||"responsive"==a||"fill"==a||"flex-item"==a||"fluid"==a||"intrinsic"==a};
V.prototype.layoutCallback=function(){var a=this,b=xa(this.win,this.element);b.title=this.element.title||"Facebook like button";this.applyFillContent(b);Ka(b,function(c){a.attemptChangeHeight(c.height).catch(function(){})});this.A=qa(this.win,this.D.bind(this));this.toggleLoading(!0);this.element.appendChild(b);this.h=b;return this.loadPromise(b)};V.prototype.D=function(a){if(!this.h||a.source==this.h.contentWindow){var b=a.data;b&&("[object Object]"===ha.call(b)?b:T(b))&&"ready"==b.action&&this.toggleLoading(!1)}};
V.prototype.unlayoutCallback=function(){if(this.h){var a=this.h;a.parentElement&&a.parentElement.removeChild(a);this.h=null}this.A&&this.A();return!0};(function(a){a.registerElement("amp-facebook-like",V)})(self.AMP);
})});

//# sourceMappingURL=amp-facebook-like-0.1.js.map
